/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    depth?: number;
                    type?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["AccountInfo"][];
                    };
                };
                /** @description Invalid `type` or `depth` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["AccountDetail"];
                    };
                };
                /** @description `name` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{name}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["BalanceReport"];
                    };
                };
                /** @description Invalid `to` or `from` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `name` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{name}/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["RegisterReport"];
                    };
                };
                /** @description Invalid `offset` or `limit` or `to` or `from` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `name` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                    account?: string;
                    description?: string;
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["PaginatedResponse"];
                    };
                };
                /** @description Invalid `offset` or `limit` or `description` or `account` or `to` or `from` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["CreateTransactionRequest"];
                };
            };
            responses: {
                201: {
                    headers: {
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["Transaction"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    index: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["Transaction"];
                    };
                };
                /** @description `index` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/import/{rules}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    dryRun?: boolean;
                };
                header?: never;
                path: {
                    rules: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["ImportResponse"];
                    };
                };
                /** @description Invalid `dryRun` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `rules` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["CreateTransactionRequest"][];
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["Transaction"][];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/balance-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    date?: string;
                    depth?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["BalanceSheetReport"];
                    };
                };
                /** @description Invalid `depth` or `date` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/income-statement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                    depth?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["IncomeStatementReport"];
                    };
                };
                /** @description Invalid `depth` or `to` or `from` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/cash-flow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["CashFlowReport"];
                    };
                };
                /** @description Invalid `to` or `from` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["VersionInfo"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commodities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["CommodityInfo"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": string[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": string[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountInfo: {
            balance: components["schemas"]["MixedAmount"];
            depth: number;
            fullName: string;
            name: string;
            subAccounts: number;
            type?: string;
        };
        /** @description A multi-currency amount (list of amounts) */
        MixedAmount: components["schemas"]["Amount"][];
        /** @description A monetary amount with commodity */
        Amount: {
            commodity: string;
            quantity: number;
        };
        AccountDetail: {
            balance?: components["schemas"]["MixedAmount"];
            fullName?: string;
            name?: string;
            parent?: string;
            subAccounts?: string[];
            type?: string;
        };
        BalanceReport: {
            account?: string;
            history?: components["schemas"]["BalanceItem"][];
            total?: components["schemas"]["MixedAmount"];
        };
        BalanceItem: {
            balance: components["schemas"]["MixedAmount"];
            /** Format: date */
            date: string;
        };
        RegisterReport: {
            account?: string;
            entries?: components["schemas"]["RegisterEntry"][];
            total?: number;
        };
        RegisterEntry: {
            amount?: components["schemas"]["MixedAmount"];
            balance?: components["schemas"]["MixedAmount"];
            /** Format: date */
            date?: string;
            description?: string;
            otherAccounts?: unknown[];
        };
        PaginatedResponse: {
            data: components["schemas"]["Transaction"][][];
            limit: number;
            offset: number;
            total: number;
        };
        Transaction: {
            code?: string;
            comment?: string;
            /** Format: date */
            date: string;
            /** Format: date */
            date2?: string;
            description: string;
            index: number;
            postings: components["schemas"]["Posting"][];
            status: components["schemas"]["Status"];
            tags?: unknown[];
        };
        /**
         * @description Transaction or posting status
         * @enum {string}
         */
        Status: "unmarked" | "pending" | "cleared";
        Posting: {
            account: string;
            amount: components["schemas"]["MixedAmount"];
            status: components["schemas"]["Status"];
        };
        CreateTransactionRequest: {
            code?: string;
            comment?: string;
            /** Format: date */
            date: string;
            /** Format: date */
            date2?: string;
            description: string;
            postings: components["schemas"]["CreatePosting"][];
            status?: components["schemas"]["Status"];
        };
        CreatePosting: {
            account: string;
            amount?: components["schemas"]["MixedAmount"];
            status?: components["schemas"]["Status"];
        };
        ImportResponse: {
            imported: number;
            skipped: number;
            transactions: components["schemas"]["Transaction"][];
        };
        BalanceSheetReport: {
            assets?: components["schemas"]["ReportSection"];
            /** Format: date */
            date?: string;
            equity?: components["schemas"]["ReportSection"];
            liabilities?: components["schemas"]["ReportSection"];
            netWorth?: components["schemas"]["MixedAmount"];
        };
        ReportSection: {
            rows?: components["schemas"]["ReportRow"][];
            title?: string;
            total?: components["schemas"]["MixedAmount"];
        };
        ReportRow: {
            account?: string;
            amount?: components["schemas"]["MixedAmount"];
            depth?: number;
        };
        IncomeStatementReport: {
            expenses?: components["schemas"]["ReportSection"];
            /** Format: date */
            from?: string;
            netIncome?: components["schemas"]["MixedAmount"];
            revenues?: components["schemas"]["ReportSection"];
            /** Format: date */
            to?: string;
        };
        CashFlowReport: {
            financing?: components["schemas"]["ReportSection"];
            /** Format: date */
            from?: string;
            investing?: components["schemas"]["ReportSection"];
            netChange?: components["schemas"]["MixedAmount"];
            operating?: components["schemas"]["ReportSection"];
            /** Format: date */
            to?: string;
        };
        VersionInfo: {
            api: string;
            hledger: string;
        };
        CommodityInfo: {
            precision: number;
            symbol: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
